name: Java CI with Maven
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: build and test with Maven
        run: mvn -B -e package --file pom.xml

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-manager-artifacts
          path: |
            backend/target/*.jar
            ui-swing/target/*.jar
            
      - name: upload surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-surefire-reports
          path: backend/target/surefire-reports/**

      - name: upload dump files
        uses: actions/upload-artifact@v4
        with:
          name: backend-dumps
          path: backend/target/*.dump*
